#!/usr/bin/env bash
# install.sh — EmbedIQ Cloud OSS first-run setup.
# Checks prerequisites, generates CA + server certificates, and writes a `.env` with
# generated secrets. Idempotent-ish: refuses to clobber an existing .env without --force.
set -euo pipefail

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERTS="$ROOT/certs"
ENV_FILE="$ROOT/.env"

echo "==> EmbedIQ Cloud — setup"

# --- 1. Prerequisites ---
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is required (https://docs.docker.com/get-docker/)"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl is required"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 is required (for bcrypt password hashing)"; exit 1; }

if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "ERROR: $ENV_FILE already exists. Re-run with --force to overwrite (regenerates all secrets)."
  exit 1
fi

# --- 2. Admin credentials ---
read -r -p "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"
read -r -s -p "Admin password: " ADMIN_PASS; echo
[ -n "$ADMIN_PASS" ] || { echo "ERROR: admin password cannot be empty"; exit 1; }

# bcrypt hash via python3 (install bcrypt into the user site if missing).
if ! python3 -c "import bcrypt" >/dev/null 2>&1; then
  echo "==> Installing python 'bcrypt' (one-time)…"
  python3 -m pip install --quiet --user bcrypt
fi
ADMIN_PASS_HASH="$(ADMIN_PASS="$ADMIN_PASS" python3 -c '
import os, bcrypt
print(bcrypt.hashpw(os.environ["ADMIN_PASS"].encode(), bcrypt.gensalt()).decode())
')"

# --- 3. Certificates (10-year CA + server) ---
# Delegated to the shared, idempotent generator (also used by the CI integration job).
bash "$ROOT/scripts/gen-certs.sh"

# --- 4. Secrets + .env ---
gen() { openssl rand -hex 32; }
echo "==> Writing $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by install.sh — do NOT commit. Regenerate with: ./install.sh --force
ADMIN_USER=$ADMIN_USER
ADMIN_PASS_HASH=$ADMIN_PASS_HASH

INFLUX_USER=embediq
INFLUX_PASSWORD=$(gen)
INFLUX_ORG=embediq
INFLUX_BUCKET=telemetry
INFLUX_TOKEN=$(gen)

GRAFANA_ADMIN_PASS=$(gen)

HAWKBIT_USER=admin
HAWKBIT_ADMIN_PASS=$(gen)

INTERNAL_API_KEY=$(gen)
JWT_SECRET=$(gen)

# Consumer-bridge credential — used only by the production profile (docker-compose.prod.yml),
# where the broker is non-anonymous. The api accepts it (/internal/auth) and the bridge presents it.
INTERNAL_BRIDGE_USER=_bridge
INTERNAL_BRIDGE_PASS=$(gen)

# Days-before-expiry at which the cloud flags a certificate (GET /api/v1/system/certs).
CERT_WARN_DAYS=30

EMBEDIQ_API_URL=http://embediq-api:8080
EOF

# --- 5. Done ---
cat <<EOF

==> Setup complete.

Start the full stack:   docker compose up -d --build
Start the lite stack:   docker compose -f docker-compose.lite.yml up -d --build

Endpoints:
  API / Admin UI   http://localhost:8080   (health: /health)
  MQTT             1883 (plain) · 8883 (TLS/mTLS)
  RTSP/RTMP/HLS    8554 / 1935 / 8888 · WebRTC 8889

CA certificate (distribute to devices): $CERTS/ca.crt
Secrets were written to $ENV_FILE (git-ignored). Keep it safe.
EOF
