# app/config.py — typed application settings loaded from the environment
# @author  Ritesh Anand
# @company embediq.com | ritzylab.com
# SPDX-License-Identifier: Apache-2.0
import os
from functools import lru_cache

from pydantic import ValidationError
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Single-admin runtime configuration.

    `ADMIN_PASS_HASH` and `JWT_SECRET` are required — there is no safe default for a
    credential or a signing key, so the app fails fast if either is missing.
    """

    model_config = SettingsConfigDict(case_sensitive=True, extra="ignore")

    ADMIN_USER: str = "admin"
    ADMIN_PASS_HASH: str
    JWT_SECRET: str
    DB_PATH: str = "/data/embediq.db"


@lru_cache
def get_settings() -> Settings:
    try:
        return Settings()  # type: ignore[call-arg]  # values come from the environment
    except ValidationError as exc:
        missing = ", ".join(str(e["loc"][0]) for e in exc.errors())
        raise RuntimeError(
            f"Missing/invalid required configuration: {missing}. "
            "Set ADMIN_PASS_HASH and JWT_SECRET (see .env.example / run ./install.sh)."
        ) from exc


class BridgeSettings(BaseSettings):
    """MQTT-bridge + backend configuration.

    Kept separate from `Settings` (and with no required fields) so the bridge and app
    startup never depend on the admin secrets — `/health` must come up regardless.
    Internal service URLs are config defaults, not secrets.
    """

    model_config = SettingsConfigDict(case_sensitive=True, extra="ignore")

    BRIDGE_ENABLED: bool = True
    MQTT_HOST: str = "mosquitto"
    MQTT_PORT: int = 1883
    # Optional broker credentials for the consumer bridge. Empty in dev (anonymous broker);
    # set in the prod profile, where the go-auth plugin requires auth (see /internal/auth).
    MQTT_USERNAME: str = ""
    MQTT_PASSWORD: str = ""
    INFLUX_URL: str = "http://influxdb:8086"
    INFLUX_TOKEN: str = ""
    INFLUX_ORG: str = "embediq"
    INFLUX_BUCKET: str = "telemetry"
    LOKI_URL: str = "http://loki:3100"


def get_bridge_settings() -> BridgeSettings:
    # Not cached: read fresh so tests can toggle BRIDGE_ENABLED per case.
    return BridgeSettings()


class HawkbitSettings(BaseSettings):
    """Hawkbit (OTA) proxy configuration. No required fields so startup never depends on it."""

    model_config = SettingsConfigDict(case_sensitive=True, extra="ignore")

    HAWKBIT_URL: str = "http://hawkbit:8080"
    HAWKBIT_USER: str = "admin"
    HAWKBIT_ADMIN_PASS: str = ""
    INTERNAL_API_KEY: str = ""


def get_hawkbit_settings() -> HawkbitSettings:
    return HawkbitSettings()


def get_cert_warn_days() -> int:
    """Days-before-expiry at which a certificate is flagged. Read fresh (not cached) so
    operators can tune it via the environment without a restart; never a secret."""
    try:
        return int(os.environ.get("CERT_WARN_DAYS", "30"))
    except ValueError:
        return 30


def get_internal_api_key() -> str:
    """Shared secret guarding the public /internal/* endpoints. Read fresh (not cached) so
    tests and operators can set it via the environment. Empty = enforcement off (dev)."""
    return os.environ.get("INTERNAL_API_KEY", "")


def is_production() -> bool:
    """True when the production profile is active (docker-compose.prod.yml sets EMBEDIQ_PROFILE)."""
    return os.environ.get("EMBEDIQ_PROFILE", "dev").strip().lower() in ("prod", "production")


def assert_internal_key_in_prod() -> None:
    """Fail closed: in production the /internal shared secret is mandatory, so the unauthenticated
    allow/deny oracles are never exposed without a key. Raises at startup if prod + empty key."""
    if is_production() and not get_internal_api_key():
        raise RuntimeError(
            "INTERNAL_API_KEY must be set in the production profile (EMBEDIQ_PROFILE=prod): the "
            "/internal endpoints require a shared secret. Set it in .env (generated by install.sh)."
        )
